// Generated from the public-domain Free Exercise DB (github.com/yuhonas/free-exercise-db, Unlicense)
// for images, muscles and equipment. Step-by-step instructions are our own, kept short on purpose.

import type { ImageSourcePropType } from 'react-native';

export type ExerciseInfo = {
  name: string;
  muscles: string[];
  equipment: string;
  steps: string[];
  /** Start and end positions; alternating them shows the movement. */
  images: [ImageSourcePropType, ImageSourcePropType];
};

/** The built-in catalogue, sorted A–Z. Custom exercises typed by the user aren't in here. */
export const EXERCISE_CATALOG: ExerciseInfo[] = [
  {
    name: "Ab Wheel Rollout",
    muscles: ["Abdominals"],
    equipment: "Other",
    steps: ["Kneel holding the wheel under your shoulders.", "Brace your abs and roll forward slowly, keeping your back flat.", "Go as far as you can without your hips sagging.", "Pull back to the start using your abs, not your hips."],
    images: [require('@/assets/exercises/ab-wheel-rollout-0.jpg'), require('@/assets/exercises/ab-wheel-rollout-1.jpg')],
  },
  {
    name: "Arnold Press",
    muscles: ["Shoulders"],
    equipment: "Dumbbell",
    steps: ["Sit tall holding dumbbells at chin height, palms facing you.", "Press up while rotating your palms to face forward.", "Finish with arms straight overhead.", "Reverse the rotation as you lower back to the start."],
    images: [require('@/assets/exercises/arnold-press-0.jpg'), require('@/assets/exercises/arnold-press-1.jpg')],
  },
  {
    name: "Barbell Row",
    muscles: ["Middle Back"],
    equipment: "Barbell",
    steps: ["Hold the bar with an overhand grip, hinge forward to about 45°.", "Keep your back flat and the bar hanging at arm's length.", "Pull the bar to your lower ribs, squeezing your shoulder blades.", "Lower under control."],
    images: [require('@/assets/exercises/barbell-row-0.jpg'), require('@/assets/exercises/barbell-row-1.jpg')],
  },
  {
    name: "Bench Press",
    muscles: ["Chest"],
    equipment: "Barbell",
    steps: ["Lie on the bench, eyes under the bar, feet flat.", "Grip slightly wider than shoulders and unrack with straight arms.", "Lower the bar to mid-chest with elbows at about 45°.", "Press back up until your arms are straight."],
    images: [require('@/assets/exercises/bench-press-0.jpg'), require('@/assets/exercises/bench-press-1.jpg')],
  },
  {
    name: "Bicep Curl",
    muscles: ["Biceps"],
    equipment: "Barbell",
    steps: ["Stand tall holding the bar at hip height, palms forward.", "Keep your elbows pinned to your sides.", "Curl the bar up to your shoulders.", "Lower slowly until your arms are straight."],
    images: [require('@/assets/exercises/bicep-curl-0.jpg'), require('@/assets/exercises/bicep-curl-1.jpg')],
  },
  {
    name: "Cable Crossover",
    muscles: ["Chest"],
    equipment: "Cable",
    steps: ["Set both pulleys high and grab a handle in each hand.", "Step forward with a slight lean and soft elbows.", "Bring your hands together in front of your hips in a wide arc.", "Return slowly until you feel a stretch across your chest."],
    images: [require('@/assets/exercises/cable-crossover-0.jpg'), require('@/assets/exercises/cable-crossover-1.jpg')],
  },
  {
    name: "Calf Raise",
    muscles: ["Calves"],
    equipment: "Machine",
    steps: ["Stand with the balls of your feet on the platform, heels hanging off.", "Keep your legs straight and core tight.", "Rise onto your toes as high as you can.", "Lower until your heels drop below the platform."],
    images: [require('@/assets/exercises/calf-raise-0.jpg'), require('@/assets/exercises/calf-raise-1.jpg')],
  },
  {
    name: "Chest Dip",
    muscles: ["Chest"],
    equipment: "Other",
    steps: ["Support yourself on the bars with straight arms.", "Lean your torso forward slightly.", "Lower until your shoulders are just below your elbows.", "Press back up to straight arms."],
    images: [require('@/assets/exercises/chest-dip-0.jpg'), require('@/assets/exercises/chest-dip-1.jpg')],
  },
  {
    name: "Chin Up",
    muscles: ["Lats"],
    equipment: "Body Only",
    steps: ["Hang from the bar with palms facing you, shoulder-width apart.", "Brace your core and pull your shoulders down.", "Pull until your chin clears the bar.", "Lower all the way to a dead hang."],
    images: [require('@/assets/exercises/chin-up-0.jpg'), require('@/assets/exercises/chin-up-1.jpg')],
  },
  {
    name: "Close-Grip Bench Press",
    muscles: ["Triceps"],
    equipment: "Barbell",
    steps: ["Lie on the bench and grip the bar at shoulder width.", "Unrack and hold it over your chest.", "Lower to your lower chest, keeping elbows tucked.", "Press up by straightening your arms."],
    images: [require('@/assets/exercises/close-grip-bench-press-0.jpg'), require('@/assets/exercises/close-grip-bench-press-1.jpg')],
  },
  {
    name: "Concentration Curl",
    muscles: ["Biceps"],
    equipment: "Dumbbell",
    steps: ["Sit on a bench, elbow resting against your inner thigh.", "Hold a dumbbell with your arm straight.", "Curl it toward your shoulder without moving your upper arm.", "Lower slowly and repeat, then switch arms."],
    images: [require('@/assets/exercises/concentration-curl-0.jpg'), require('@/assets/exercises/concentration-curl-1.jpg')],
  },
  {
    name: "Crunch",
    muscles: ["Abdominals"],
    equipment: "Body Only",
    steps: ["Lie on your back, knees bent, hands by your head.", "Brace your abs and curl your shoulders off the floor.", "Pause and squeeze at the top.", "Lower slowly without letting your head drop."],
    images: [require('@/assets/exercises/crunch-0.jpg'), require('@/assets/exercises/crunch-1.jpg')],
  },
  {
    name: "Deadlift",
    muscles: ["Lower Back"],
    equipment: "Barbell",
    steps: ["Stand with mid-foot under the bar, feet hip-width.", "Hinge down and grip the bar just outside your legs.", "Brace, flatten your back and push the floor away to stand up.", "Lower by pushing your hips back, bar close to your legs."],
    images: [require('@/assets/exercises/deadlift-0.jpg'), require('@/assets/exercises/deadlift-1.jpg')],
  },
  {
    name: "Dumbbell Bench Press",
    muscles: ["Chest"],
    equipment: "Dumbbell",
    steps: ["Lie on a bench holding dumbbells at chest level.", "Plant your feet and squeeze your shoulder blades together.", "Press the dumbbells up until your arms are straight.", "Lower slowly to chest level."],
    images: [require('@/assets/exercises/dumbbell-bench-press-0.jpg'), require('@/assets/exercises/dumbbell-bench-press-1.jpg')],
  },
  {
    name: "Dumbbell Fly",
    muscles: ["Chest"],
    equipment: "Dumbbell",
    steps: ["Lie on a bench holding dumbbells above your chest, palms facing.", "Keep a slight bend in your elbows.", "Open your arms wide until you feel a chest stretch.", "Bring the dumbbells back together in an arc."],
    images: [require('@/assets/exercises/dumbbell-fly-0.jpg'), require('@/assets/exercises/dumbbell-fly-1.jpg')],
  },
  {
    name: "Dumbbell Row",
    muscles: ["Middle Back"],
    equipment: "Dumbbell",
    steps: ["Put one knee and hand on a bench, back flat.", "Hold a dumbbell in the other hand, arm straight.", "Pull the dumbbell to your hip, elbow close to your body.", "Lower under control, then switch sides."],
    images: [require('@/assets/exercises/dumbbell-row-0.jpg'), require('@/assets/exercises/dumbbell-row-1.jpg')],
  },
  {
    name: "Dumbbell Shoulder Press",
    muscles: ["Shoulders"],
    equipment: "Dumbbell",
    steps: ["Sit tall holding dumbbells at shoulder height, palms forward.", "Brace your core and keep your back against the bench.", "Press up until your arms are straight overhead.", "Lower back to shoulder height."],
    images: [require('@/assets/exercises/dumbbell-shoulder-press-0.jpg'), require('@/assets/exercises/dumbbell-shoulder-press-1.jpg')],
  },
  {
    name: "Face Pull",
    muscles: ["Shoulders"],
    equipment: "Cable",
    steps: ["Set a rope on a high pulley and grab both ends.", "Step back so your arms are straight.", "Pull the rope toward your face, elbows high and wide.", "Squeeze your upper back, then return slowly."],
    images: [require('@/assets/exercises/face-pull-0.jpg'), require('@/assets/exercises/face-pull-1.jpg')],
  },
  {
    name: "Front Squat",
    muscles: ["Quadriceps"],
    equipment: "Barbell",
    steps: ["Rest the bar on the front of your shoulders, elbows high.", "Stand with feet shoulder-width, toes slightly out.", "Squat down keeping your chest up and elbows high.", "Drive up through your mid-foot."],
    images: [require('@/assets/exercises/front-squat-0.jpg'), require('@/assets/exercises/front-squat-1.jpg')],
  },
  {
    name: "Glute Bridge",
    muscles: ["Glutes"],
    equipment: "Barbell",
    steps: ["Lie on your back with knees bent and the bar over your hips.", "Plant your feet flat, hip-width apart.", "Drive your hips up until your body is straight from knees to shoulders.", "Squeeze your glutes, then lower slowly."],
    images: [require('@/assets/exercises/glute-bridge-0.jpg'), require('@/assets/exercises/glute-bridge-1.jpg')],
  },
  {
    name: "Goblet Squat",
    muscles: ["Quadriceps"],
    equipment: "Kettlebells",
    steps: ["Hold a dumbbell or kettlebell at your chest.", "Stand with feet just wider than shoulders.", "Squat down between your knees, chest up.", "Stand back up by pushing through your heels."],
    images: [require('@/assets/exercises/goblet-squat-0.jpg'), require('@/assets/exercises/goblet-squat-1.jpg')],
  },
  {
    name: "Hack Squat",
    muscles: ["Quadriceps"],
    equipment: "Machine",
    steps: ["Stand on the platform with your back against the pad.", "Place feet shoulder-width and release the safety handles.", "Lower until your thighs are at least parallel.", "Push back up without locking your knees."],
    images: [require('@/assets/exercises/hack-squat-0.jpg'), require('@/assets/exercises/hack-squat-1.jpg')],
  },
  {
    name: "Hammer Curl",
    muscles: ["Biceps"],
    equipment: "Dumbbell",
    steps: ["Stand holding dumbbells at your sides, palms facing in.", "Keep your elbows fixed by your torso.", "Curl the dumbbells up, keeping palms facing in.", "Lower slowly to the start."],
    images: [require('@/assets/exercises/hammer-curl-0.jpg'), require('@/assets/exercises/hammer-curl-1.jpg')],
  },
  {
    name: "Hanging Leg Raise",
    muscles: ["Abdominals"],
    equipment: "Body Only",
    steps: ["Hang from a bar with straight arms.", "Brace your core to stop swinging.", "Raise your legs until they're parallel to the floor or higher.", "Lower slowly under control."],
    images: [require('@/assets/exercises/hanging-leg-raise-0.jpg'), require('@/assets/exercises/hanging-leg-raise-1.jpg')],
  },
  {
    name: "Hip Thrust",
    muscles: ["Glutes"],
    equipment: "Barbell",
    steps: ["Sit with your upper back against a bench, bar over your hips.", "Plant your feet flat, knees bent.", "Drive through your heels to lift your hips until level with your torso.", "Squeeze your glutes at the top, then lower."],
    images: [require('@/assets/exercises/hip-thrust-0.jpg'), require('@/assets/exercises/hip-thrust-1.jpg')],
  },
  {
    name: "Incline Bench Press",
    muscles: ["Chest"],
    equipment: "Barbell",
    steps: ["Set the bench to 30–45° and lie back under the bar.", "Grip slightly wider than shoulders and unrack.", "Lower the bar to your upper chest.", "Press back up to straight arms."],
    images: [require('@/assets/exercises/incline-bench-press-0.jpg'), require('@/assets/exercises/incline-bench-press-1.jpg')],
  },
  {
    name: "Incline Dumbbell Press",
    muscles: ["Chest"],
    equipment: "Dumbbell",
    steps: ["Set the bench to 30–45° and hold dumbbells at shoulder level.", "Plant your feet and keep your back on the bench.", "Press up until your arms are straight.", "Lower slowly to upper-chest level."],
    images: [require('@/assets/exercises/incline-dumbbell-press-0.jpg'), require('@/assets/exercises/incline-dumbbell-press-1.jpg')],
  },
  {
    name: "Kettlebell Swing",
    muscles: ["Hamstrings"],
    equipment: "Kettlebells",
    steps: ["Stand with feet wide, kettlebell on the floor in front.", "Hinge and hike the bell back between your legs.", "Snap your hips forward to swing it to chest height.", "Let it fall back and hinge into the next rep."],
    images: [require('@/assets/exercises/kettlebell-swing-0.jpg'), require('@/assets/exercises/kettlebell-swing-1.jpg')],
  },
  {
    name: "Lat Pulldown",
    muscles: ["Lats"],
    equipment: "Cable",
    steps: ["Sit with thighs under the pad and grip the bar wide.", "Lean back slightly and lift your chest.", "Pull the bar to your upper chest, elbows down and back.", "Let the bar rise slowly until your arms are straight."],
    images: [require('@/assets/exercises/lat-pulldown-0.jpg'), require('@/assets/exercises/lat-pulldown-1.jpg')],
  },
  {
    name: "Lateral Raise",
    muscles: ["Shoulders"],
    equipment: "Dumbbell",
    steps: ["Stand holding dumbbells at your sides.", "Keep a slight bend in your elbows.", "Raise your arms out to the sides to shoulder height.", "Lower slowly, don't swing."],
    images: [require('@/assets/exercises/lateral-raise-0.jpg'), require('@/assets/exercises/lateral-raise-1.jpg')],
  },
  {
    name: "Leg Curl",
    muscles: ["Hamstrings"],
    equipment: "Machine",
    steps: ["Lie face down with the pad just above your heels.", "Grip the handles and keep your hips on the bench.", "Curl your heels toward your glutes.", "Lower slowly to straight legs."],
    images: [require('@/assets/exercises/leg-curl-0.jpg'), require('@/assets/exercises/leg-curl-1.jpg')],
  },
  {
    name: "Leg Extension",
    muscles: ["Quadriceps"],
    equipment: "Machine",
    steps: ["Sit with the pad on your lower shins, knees at the seat edge.", "Grip the handles and sit tall.", "Straighten your legs until fully extended.", "Lower slowly back to the start."],
    images: [require('@/assets/exercises/leg-extension-0.jpg'), require('@/assets/exercises/leg-extension-1.jpg')],
  },
  {
    name: "Leg Press",
    muscles: ["Quadriceps"],
    equipment: "Machine",
    steps: ["Sit with your back flat and feet shoulder-width on the platform.", "Release the safety and straighten your legs without locking them.", "Lower until your knees are at about 90°.", "Push back up through your heels."],
    images: [require('@/assets/exercises/leg-press-0.jpg'), require('@/assets/exercises/leg-press-1.jpg')],
  },
  {
    name: "Lunge",
    muscles: ["Quadriceps"],
    equipment: "Dumbbell",
    steps: ["Stand holding dumbbells at your sides.", "Step forward and lower until both knees are at 90°.", "Keep your front knee over your ankle.", "Push off the front foot back to standing, then switch legs."],
    images: [require('@/assets/exercises/lunge-0.jpg'), require('@/assets/exercises/lunge-1.jpg')],
  },
  {
    name: "Mountain Climber",
    muscles: ["Quadriceps"],
    equipment: "Body Only",
    steps: ["Start in a high plank, hands under shoulders.", "Drive one knee toward your chest.", "Switch legs quickly, like running in place.", "Keep your hips level the whole time."],
    images: [require('@/assets/exercises/mountain-climber-0.jpg'), require('@/assets/exercises/mountain-climber-1.jpg')],
  },
  {
    name: "Overhead Press",
    muscles: ["Shoulders"],
    equipment: "Barbell",
    steps: ["Stand holding the bar at shoulder height, hands just outside shoulders.", "Brace your core and glutes.", "Press the bar straight up, moving your head back then through.", "Lower to your shoulders under control."],
    images: [require('@/assets/exercises/overhead-press-0.jpg'), require('@/assets/exercises/overhead-press-1.jpg')],
  },
  {
    name: "Plank",
    muscles: ["Abdominals"],
    equipment: "Body Only",
    steps: ["Rest on your forearms and toes, elbows under shoulders.", "Keep your body in a straight line from head to heels.", "Brace your abs and squeeze your glutes.", "Hold for time while breathing steadily."],
    images: [require('@/assets/exercises/plank-0.jpg'), require('@/assets/exercises/plank-1.jpg')],
  },
  {
    name: "Preacher Curl",
    muscles: ["Biceps"],
    equipment: "Barbell",
    steps: ["Sit at the preacher bench with your arms over the pad.", "Hold the bar with palms up, arms nearly straight.", "Curl the bar toward your shoulders.", "Lower slowly until your arms are almost straight."],
    images: [require('@/assets/exercises/preacher-curl-0.jpg'), require('@/assets/exercises/preacher-curl-1.jpg')],
  },
  {
    name: "Pull Up",
    muscles: ["Lats"],
    equipment: "Body Only",
    steps: ["Hang from the bar with palms facing away, slightly wider than shoulders.", "Pull your shoulders down and brace.", "Pull until your chin clears the bar.", "Lower all the way down with control."],
    images: [require('@/assets/exercises/pull-up-0.jpg'), require('@/assets/exercises/pull-up-1.jpg')],
  },
  {
    name: "Push Up",
    muscles: ["Chest"],
    equipment: "Body Only",
    steps: ["Start in a high plank, hands slightly wider than shoulders.", "Keep your body straight from head to heels.", "Lower until your chest nearly touches the floor.", "Push back up to straight arms."],
    images: [require('@/assets/exercises/push-up-0.jpg'), require('@/assets/exercises/push-up-1.jpg')],
  },
  {
    name: "Rear Delt Fly",
    muscles: ["Shoulders"],
    equipment: "Dumbbell",
    steps: ["Hinge forward holding dumbbells under your chest.", "Keep a slight bend in your elbows.", "Raise your arms out to the sides, squeezing your upper back.", "Lower slowly."],
    images: [require('@/assets/exercises/rear-delt-fly-0.jpg'), require('@/assets/exercises/rear-delt-fly-1.jpg')],
  },
  {
    name: "Romanian Deadlift",
    muscles: ["Hamstrings"],
    equipment: "Barbell",
    steps: ["Stand holding the bar at your thighs, knees soft.", "Push your hips back, sliding the bar down your legs.", "Stop when you feel a hamstring stretch, back flat.", "Drive your hips forward to stand up."],
    images: [require('@/assets/exercises/romanian-deadlift-0.jpg'), require('@/assets/exercises/romanian-deadlift-1.jpg')],
  },
  {
    name: "Russian Twist",
    muscles: ["Abdominals"],
    equipment: "Body Only",
    steps: ["Sit with knees bent and lean back to about 45°.", "Hold your hands or a weight in front of your chest.", "Rotate your torso to one side, then the other.", "Keep your chest up and core tight."],
    images: [require('@/assets/exercises/russian-twist-0.jpg'), require('@/assets/exercises/russian-twist-1.jpg')],
  },
  {
    name: "Seated Cable Row",
    muscles: ["Middle Back"],
    equipment: "Cable",
    steps: ["Sit with feet on the platform and grab the handle.", "Sit tall with a slight knee bend.", "Pull the handle to your stomach, squeezing your shoulder blades.", "Return slowly until your arms are straight."],
    images: [require('@/assets/exercises/seated-cable-row-0.jpg'), require('@/assets/exercises/seated-cable-row-1.jpg')],
  },
  {
    name: "Seated Calf Raise",
    muscles: ["Calves"],
    equipment: "Machine",
    steps: ["Sit with the pad on your lower thighs, balls of feet on the platform.", "Release the safety.", "Raise your heels as high as you can.", "Lower until you feel a stretch in your calves."],
    images: [require('@/assets/exercises/seated-calf-raise-0.jpg'), require('@/assets/exercises/seated-calf-raise-1.jpg')],
  },
  {
    name: "Shrug",
    muscles: ["Traps"],
    equipment: "Dumbbell",
    steps: ["Stand holding dumbbells at your sides.", "Keep your arms straight.", "Lift your shoulders straight up toward your ears.", "Hold briefly, then lower."],
    images: [require('@/assets/exercises/shrug-0.jpg'), require('@/assets/exercises/shrug-1.jpg')],
  },
  {
    name: "Sit Up",
    muscles: ["Abdominals"],
    equipment: "Body Only",
    steps: ["Lie on your back, knees bent, feet anchored.", "Cross your arms or place hands by your head.", "Curl your torso up until you're sitting upright.", "Lower back down slowly."],
    images: [require('@/assets/exercises/sit-up-0.jpg'), require('@/assets/exercises/sit-up-1.jpg')],
  },
  {
    name: "Skull Crusher",
    muscles: ["Triceps"],
    equipment: "E-Z Curl Bar",
    steps: ["Lie on a bench holding an EZ bar over your chest.", "Keep your upper arms still and pointing up.", "Bend your elbows to lower the bar toward your forehead.", "Straighten your arms to press it back up."],
    images: [require('@/assets/exercises/skull-crusher-0.jpg'), require('@/assets/exercises/skull-crusher-1.jpg')],
  },
  {
    name: "Split Squat",
    muscles: ["Quadriceps"],
    equipment: "Dumbbell",
    steps: ["Stand in a long stride holding dumbbells at your sides.", "Keep your torso upright.", "Lower straight down until your back knee nearly touches the floor.", "Push back up, then switch legs."],
    images: [require('@/assets/exercises/split-squat-0.jpg'), require('@/assets/exercises/split-squat-1.jpg')],
  },
  {
    name: "Squat",
    muscles: ["Quadriceps"],
    equipment: "Barbell",
    steps: ["Set the bar on your upper back and step out of the rack.", "Stand with feet shoulder-width, toes slightly out.", "Sit your hips back and down until thighs are at least parallel.", "Drive up through your mid-foot, chest up."],
    images: [require('@/assets/exercises/squat-0.jpg'), require('@/assets/exercises/squat-1.jpg')],
  },
  {
    name: "T-Bar Row",
    muscles: ["Middle Back"],
    equipment: "Barbell",
    steps: ["Straddle the bar and grab the handle.", "Hinge forward with a flat back and soft knees.", "Pull the weight to your chest, squeezing your back.", "Lower until your arms are straight."],
    images: [require('@/assets/exercises/t-bar-row-0.jpg'), require('@/assets/exercises/t-bar-row-1.jpg')],
  },
  {
    name: "Tricep Dip",
    muscles: ["Triceps"],
    equipment: "Body Only",
    steps: ["Support yourself on the bars with straight arms.", "Keep your torso upright and elbows tucked.", "Lower until your elbows reach about 90°.", "Press back up to straight arms."],
    images: [require('@/assets/exercises/tricep-dip-0.jpg'), require('@/assets/exercises/tricep-dip-1.jpg')],
  },
  {
    name: "Tricep Pushdown",
    muscles: ["Triceps"],
    equipment: "Cable",
    steps: ["Grab the bar on a high pulley with an overhand grip.", "Pin your elbows to your sides.", "Push the bar down until your arms are straight.", "Let it rise slowly to about chest height."],
    images: [require('@/assets/exercises/tricep-pushdown-0.jpg'), require('@/assets/exercises/tricep-pushdown-1.jpg')],
  },
  {
    name: "Upright Row",
    muscles: ["Traps"],
    equipment: "Dumbbell",
    steps: ["Stand holding dumbbells in front of your thighs.", "Lift them along your body, leading with your elbows.", "Stop when your elbows reach shoulder height.", "Lower slowly."],
    images: [require('@/assets/exercises/upright-row-0.jpg'), require('@/assets/exercises/upright-row-1.jpg')],
  },
];

const byName = new Map(EXERCISE_CATALOG.map((e) => [e.name, e]));

export const findExercise = (name: string) => byName.get(name);
